<?php

namespace ContainerLg8OSzz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OTTTARlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OTTTARl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OTTTARl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cityRepo' => ['privates', 'App\\Repository\\CityRepository', 'getCityRepositoryService', true],
            'country' => ['privates', 'App\\Entity\\Country', 'getCountryService', true],
            'countryRepository' => ['privates', 'App\\Repository\\CountryRepository', 'getCountryRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'cityRepo' => 'App\\Repository\\CityRepository',
            'country' => 'App\\Entity\\Country',
            'countryRepository' => 'App\\Repository\\CountryRepository',
            'em' => '?',
            'postRepo' => 'App\\Repository\\PostRepository',
        ]);
    }
}
