<?php

namespace ContainerLg8OSzz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1bhW3hBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1bhW3hB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1bhW3hB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'city' => ['privates', 'App\\Entity\\City', 'getCityService', true],
            'cityRepository' => ['privates', 'App\\Repository\\CityRepository', 'getCityRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'placeRepo' => ['privates', 'App\\Repository\\PlaceRepository', 'getPlaceRepositoryService', true],
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'city' => 'App\\Entity\\City',
            'cityRepository' => 'App\\Repository\\CityRepository',
            'em' => '?',
            'placeRepo' => 'App\\Repository\\PlaceRepository',
            'postRepo' => 'App\\Repository\\PostRepository',
        ]);
    }
}
