<?php

namespace ContainerLg8OSzz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\City' shared autowired service.
     *
     * @return \App\Entity\City
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'City.php';

        return $container->privates['App\\Entity\\City'] = new \App\Entity\City();
    }
}
