controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_show_one_country:
    path: /country/{id}
    controller: App\Controller\CountryController::showonecountry
    requirements:
        id: \d+

user_edit:
    path: /user/{id}
    controller: App\Controller\UserController::edit
    requirements:
        id: \d+
