<?php

namespace ContainerKQPnepY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IZifd_DService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.IZifd.D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IZifd.D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepo' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'place' => ['privates', 'App\\Entity\\Place', 'getPlaceService', true],
            'placeRepo' => ['privates', 'App\\Repository\\PlaceRepository', 'getPlaceRepositoryService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'commentRepo' => 'App\\Repository\\CommentRepository',
            'em' => '?',
            'place' => 'App\\Entity\\Place',
            'placeRepo' => 'App\\Repository\\PlaceRepository',
            'urlGenerator' => '?',
        ]);
    }
}
