<?php

namespace ContainerKQPnepY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosCkEditor_InstallerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'fos_ck_editor.installer' shared service.
     *
     * @return \FOS\CKEditorBundle\Installer\CKEditorInstaller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'friendsofsymfony'.\DIRECTORY_SEPARATOR.'ckeditor-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Installer'.\DIRECTORY_SEPARATOR.'CKEditorInstaller.php';

        return $container->privates['fos_ck_editor.installer'] = new \FOS\CKEditorBundle\Installer\CKEditorInstaller();
    }
}
