<?php

namespace ContainerKQPnepY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUuid_FactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'uuid.factory' shared service.
     *
     * @return \Symfony\Component\Uid\Factory\UuidFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'uid'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'UuidFactory.php';

        return $container->privates['uuid.factory'] = new \Symfony\Component\Uid\Factory\UuidFactory(7, 7, 5, 'Symfony\\Component\\Uid\\UuidV4', NULL, NULL);
    }
}
