<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKQPnepY\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKQPnepY/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKQPnepY.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKQPnepY\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerKQPnepY\App_KernelTestDebugContainer([
    'container.build_hash' => 'KQPnepY',
    'container.build_id' => 'f48fc70d',
    'container.build_time' => 1714670031,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKQPnepY');
