<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLg8OSzz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLg8OSzz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLg8OSzz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLg8OSzz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLg8OSzz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lg8OSzz',
    'container.build_id' => 'e4545bd9',
    'container.build_time' => 1718613393,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLg8OSzz');
